#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
const eventId = process.argv[2] || "ufc-324";
const sportKey = process.argv[3] || "mma_mixed_martial_arts";
const apiKey = process.env.ODDS_API_KEY;

if (!apiKey) {
  console.error("Missing ODDS_API_KEY. Example: $env:ODDS_API_KEY='your-key'; node tools/pull-odds.mjs ufc-324 mma_mixed_martial_arts");
  process.exit(1);
}

function normalizeText(value) {
  return String(value || "")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

function americanToImplied(odds) {
  const n = Number(odds);
  if (!Number.isFinite(n) || n === 0) return null;
  return n > 0 ? 100 / (n + 100) : Math.abs(n) / (Math.abs(n) + 100);
}

function impliedToAmerican(probability) {
  const p = Number(probability);
  if (!Number.isFinite(p) || p <= 0 || p >= 1) return null;
  if (p >= 0.5) return Math.round((-100 * p) / (1 - p));
  return Math.round((100 * (1 - p)) / p);
}

function averageAmericanOdds(...values) {
  const prices = values
    .flat()
    .map((value) => Number(value))
    .filter((value) => Number.isFinite(value) && value !== 0);

  if (!prices.length) return null;

  const avgProbability =
    prices.reduce((sum, price) => sum + americanToImplied(price), 0) /
    prices.length;

  return impliedToAmerican(avgProbability);
}

function bookmakerKey(titleOrKey) {
  const key = normalizeText(titleOrKey).replaceAll(" ", "");
  if (key.includes("fanduel")) return "fanduel";
  if (key.includes("draftkings")) return "draftkings";
  return key;
}

function loadEvent(eventId) {
  const ctx = {
    window: { RISKEM_EVENTS: {}, RISKEM_EVENT_ORDER: [] },
    console,
  };

  const eventPath = path.join(ROOT, "events", `${eventId}.js`);
  if (!fs.existsSync(eventPath)) {
    throw new Error(`Missing event file: ${eventPath}`);
  }

  vm.createContext(ctx);
  vm.runInContext(fs.readFileSync(eventPath, "utf8"), ctx, { filename: eventPath });

  const event = ctx.window.RISKEM_EVENTS[eventId];
  if (!event) throw new Error(`Event ${eventId} was not registered by ${eventPath}`);
  return event;
}

function buildSnapshot(event, oddsApiEvents) {
  const snapshot = {
    sourceLabel: "FanDuel + DraftKings AVG",
    pulledAt: new Date().toISOString(),
    note: "Generated by tools/pull-odds.mjs from moneyline prices. AVG is computed from average implied probability, then converted back to American odds.",
    contests: {},
  };

  for (const contest of event.contests || []) {
    const entrantNames = (contest.entrants || []).map((entrant) => normalizeText(entrant.name));
    const apiEvent = (oddsApiEvents || []).find((candidate) => {
      const names = [candidate.home_team, candidate.away_team].map(normalizeText);
      return entrantNames.every((entrantName) => names.includes(entrantName));
    });

    snapshot.contests[contest.id] = {};

    for (const entrant of contest.entrants || []) {
      const row = { fanduel: null, draftkings: null, avg: null };

      for (const book of apiEvent?.bookmakers || []) {
        const bookKey = bookmakerKey(book.key || book.title);
        if (bookKey !== "fanduel" && bookKey !== "draftkings") continue;

        const h2h = (book.markets || []).find((market) => market.key === "h2h");
        const outcome = (h2h?.outcomes || []).find(
          (out) => normalizeText(out.name) === normalizeText(entrant.name),
        );

        if (outcome?.price !== undefined) row[bookKey] = Number(outcome.price);
      }

      row.avg = averageAmericanOdds(row.fanduel, row.draftkings);
      snapshot.contests[contest.id][entrant.id] = row;
    }
  }

  return snapshot;
}

function snapshotJs(eventId, snapshot) {
  return `window.RISKEM_ODDS_SNAPSHOTS = window.RISKEM_ODDS_SNAPSHOTS || {};\n\nwindow.RISKEM_ODDS_SNAPSHOTS[${JSON.stringify(eventId)}] = ${JSON.stringify(snapshot, null, 2)};\n\nwindow.RISKEM_APPLY_ODDS_SNAPSHOT?.(${JSON.stringify(eventId)});\n`;
}

const event = loadEvent(eventId);
const url = new URL(`https://api.the-odds-api.com/v4/sports/${sportKey}/odds/`);
url.searchParams.set("apiKey", apiKey);
url.searchParams.set("regions", "us");
url.searchParams.set("markets", "h2h");
url.searchParams.set("oddsFormat", "american");
url.searchParams.set("bookmakers", "fanduel,draftkings");

console.log(`Pulling ${eventId} from ${url.origin}${url.pathname} ...`);
const response = await fetch(url);
if (!response.ok) {
  const body = await response.text();
  throw new Error(`Odds API failed ${response.status}: ${body}`);
}

const oddsApiEvents = await response.json();
const snapshot = buildSnapshot(event, oddsApiEvents);
const outDir = path.join(ROOT, "events", "odds");
fs.mkdirSync(outDir, { recursive: true });
const outFile = path.join(outDir, `${eventId}-odds.js`);
fs.writeFileSync(outFile, snapshotJs(eventId, snapshot));

console.log(`Wrote ${path.relative(ROOT, outFile)}`);
for (const [contestId, entrants] of Object.entries(snapshot.contests)) {
  const line = Object.entries(entrants)
    .map(([entrantId, row]) => `${entrantId}: FD ${row.fanduel ?? "—"}, DK ${row.draftkings ?? "—"}, AVG ${row.avg ?? "—"}`)
    .join(" | ");
  console.log(`${contestId}: ${line}`);
}
